baseURL = "https://shafyy.com/"
theme = "hugo-journal"
languageCode = "en-us"
title = "shafyy's blog"

[params]
  description = "shafyy's personal blog where he rambles on about technology, startups, and other fun topics. You should check it out."
  twitterUsername = "canolcer"
  #tagline = "What I think about stuff."
