baseURL = "https://canolcer.com/"
theme = "hugo-journal"
languageCode = "en-us"
title = "Can's blog"

[params]
  description = "Can's thoughts and opinions on the world."
  twitterUsername = "canolcer"
  #tagline = "What I think about stuff."

[markup.goldmark.renderer]
  unsafe= true